---
title: "GazeScorer model analysis using L2CS code"
output: html_notebook
---
```{r}

```

```{r}
library(tidyverse)
library(glue)
library(ez)

results <- read_csv(paste0("../.output/L2CS_NCO_new/", "/results.csv")) %>%
  mutate(video = str_replace(video, "_processed\\.mp4", ""))

study_data <- read_csv(paste0("../.output/L2CS_NCO_new/", "number_comparison_online.csv")) %>%
  mutate(
    video = str_replace(vid_fname, "(_processed)?\\.(webm|mp4)", ""),
    Correct = if_else(Correct == 1, "Correct", "Incorrect")
  ) %>%
  select(-X1)

results_full <- results

results <- results_full %>% 
  group_by(video) %>%
  summarise(
    face_count = max(face_count),
    p_looks_right = mean(pitch > 0)
  )

results <- results %>% 
  left_join(study_data, by = c("video")) %>%
  filter(!str_starts(PID, "test"))

results %>% group_by(Response) %>% summarise(n = n())

results_with_to <- results

results <- results %>% filter(Response != "2")

results %>% group_by(face_count) %>% summarise(n = n())

results_all_faces <- results

results <- results_all_faces %>% filter(face_count == 1)

```

Basic visulisation.

```{r}

ggplot(results, aes(x = p_looks_right, fill = Response)) +
  geom_histogram(position = "identity", alpha = 1/3) + 
  ggtitle("Probability of video being rightward look")

```
Basic accuracy

```{r}

results %>% 
  group_by(Correct, Response) %>%
  summarise(n = n(), p_right_look = mean(p_looks_right > .5))

ggplot(results, aes(x = Response, y = p_looks_right, colour = Correct)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = "jitter", alpha = 0.2)


```

Accuracy by participant

```{r}


ggplot(results, aes(x = Response, y = p_looks_right, colour = Correct)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = "jitter", alpha = 0.2) +
  facet_wrap(~PID)

```
## Stats.

ANOVA of Correct x Response

```{r}

results_with_all <- results %>%
  nest(data = -PID) %>%
  mutate(data = map(data, function(d) {
    row_count <- d %>% group_by(Correct, Response) %>% summarise(n = n(), .groups = "drop")
    if (nrow(row_count) == 4)
      d
    else
      NA
  })) %>%
  filter(!is.na(data)) %>%
  unnest(data)

ezANOVA(
  data = results_with_all,
  dv = p_looks_right,
  wid = PID,
  within = c(Correct, Response)
)

```

T-test of Response

```{r}

.summary <- results %>% 
  group_by(PID, Response) %>% 
  summarise(p_looks_right = mean(p_looks_right), .groups = "drop")

ggplot(.summary, aes(x = Response, y = p_looks_right)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = "jitter", alpha = 0.2)

t.test(p_looks_right ~ Response, data = .summary)

```

Paired T-test dropping participants who don't give both responses.

```{r}

results_with_both <- results %>%
  nest(data = -PID) %>%
  mutate(data = map(data, function(d) {
    row_count <- d %>% group_by(Response) %>% summarise(n = n(), .groups = "drop")
    if (nrow(row_count) == 2)
      d
    else
      NA
  })) %>%
  filter(!is.na(data)) %>%
  unnest(data) %>%
  group_by(PID, Response) %>% 
  summarise(p_looks_right = mean(p_looks_right), .groups = "drop")

ggplot(results_with_both, aes(x = Response, y = p_looks_right)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = "jitter", alpha = 0.2)

t.test(
  x = results_with_both %>% filter(Response == "Right") %>% pull(p_looks_right),
  y = results_with_both %>% filter(Response == "Left") %>% pull(p_looks_right),
  paired = T
)

```
