---
title: "GazeScorer model analysis using L2CS code"
output: html_notebook
---

```{r}
library(tidyverse)
library(glue)

results <- read_csv(paste0("../.output/monkshood/", "/results.csv")) %>%
  mutate(source = 'L2CS')

et_info_all <- read_csv(paste0("../.output/monkshood/", "ET_output_results.csv"))

et_info_ok <- et_info_all %>% filter(str_starts(status, "0"))

et_info_highpass <- et_info_ok %>% filter(abs(left_gaze_x) > 0.5)

et_info <- et_info_highpass %>%
  rename(ET_class = actual_class) %>%
  mutate(ET_class = case_when(left_gaze_x < 0 ~ 'left', left_gaze_x > 0 ~ 'right', T ~ 'centre')) %>%
  select(video, frame, ET_class, left_gaze_x)

results <- results %>%
  left_join(et_info, by = c("video", "frame")) %>%
  select(-actual_class)

results %>% 
  group_by(ET_class) %>%
  summarise(n = n())

results %>% 
  filter(is.na(ET_class) | ET_class == "centre") %>%
  group_by(ET_class, video) %>%
  summarise(n_dropped_frames = n()) %>%
  arrange(desc(ET_class))

dropped_no_et_class <- results %>% filter(is.na(ET_class))
results <- results %>% filter(!is.na(ET_class))

dropped_et_centre <- results %>% filter(ET_class == "centre")
results <- results %>% filter(ET_class != "centre")
results_with_centre <- bind_rows(dropped_et_centre, results)

results <- results %>% mutate(correct = predicted_class == ET_class)

glue("Dropped {nrow(dropped_no_et_class)} frames from for having no EyeTracker class")
glue("Dropped {nrow(dropped_et_centre)} frames for having EyeTracker class='centre'")

```

Basic visulisation.

```{r}

ggplot(results, aes(y = yaw, x = pitch, colour = correct)) +
  geom_point(alpha = 0.2) +
  ggtitle(glue("Gaze direction verdicts")) +
  theme(legend.position = "top")

ggplot(results_with_centre, aes(x = pitch, fill = ET_class)) +
  geom_histogram(position = "identity", alpha = 1/3) + 
  ggtitle("Pitch")

ggplot(results_with_centre, aes(y = yaw)) +
  geom_histogram() + 
  ggtitle("Yaw")

ggplot(results_with_centre, aes(x = pitch, y = yaw)) + 
  geom_point(alpha = .01)

results_with_centre %>% 
  mutate(sides_match = ((pitch < 0) == (left_gaze_x < 0))) %>%
  ggplot(aes(x = pitch, y = left_gaze_x, colour = sides_match)) +
  geom_point(alpha = 0.1) +
  geom_abline(slope = 1, intercept = 0)

```
Basic accuracy

```{r}

ggplot(results, aes(y = yaw, x = pitch, colour = correct)) +
  geom_point(alpha = 0.2) +
  ggtitle(glue("Gaze direction verdicts")) +
  theme(legend.position = "top")

mean_cl_normal(results$correct)

results %>% 
  group_by(ET_class) %>%
  summarise(accuracy = mean(correct))

results %>% summarise(accuracy = mean(correct))

results %>% 
  filter(face_count < 2) %>%
  group_by(ET_class) %>% 
  summarise(accuracy = mean(correct))

```

Prediction with frames combined.

```{r}

frame_average <- results %>% 
  group_by(video, actual_class, face_count) %>%
  summarise(
    mean_pitch = mean(pitch), 
    frame_count = n(),
    .groups = "drop"
  ) %>%
  mutate(
    predicted_class = if_else(mean_pitch < 0, 'left', 'right'),
    correct = predicted_class == actual_class
  )

ggplot(frame_average, aes(x = mean_pitch, fill = actual_class)) +
  geom_histogram(alpha = 1/3, position = position_identity()) +
  ggtitle(glue("Predictive accuracy of classification (frames averaged)")) +
  theme(legend.position = "top")

ggplot(frame_average, aes(x = mean_pitch, y = frame_count, colour = actual_class)) +
  geom_point(alpha = 0.2) +
  ggtitle("Accuracy by direction and frame count") +
  theme(legend.position = "top")

frame_average %>%
  summarise(accuracy = mean(correct))

frame_average %>% 
  group_by(actual_class, face_count) %>%
  summarise(mean(correct))

accuracy_by_frame_count <- frame_average %>%
  mutate(frames = cut(frame_count, 10)) %>%
  group_by(frames) %>%
  summarise(accuracy = mean(correct), n = n())
accuracy_by_frame_count

ggplot(accuracy_by_frame_count, aes(x = frames, y = accuracy)) +
  geom_point()

# videos with errors
frame_average %>% 
  filter(!correct) %>%
  select(video, face_count, frame_count, mean_pitch, correct) %>%
  arrange(-abs(mean_pitch), -face_count, -frame_count)

# errors by participant video
frame_average %>%
  mutate(participant = str_extract(video, "^[^_]+")) %>%
  group_by(participant, correct) %>% 
  summarise(n = n()) %>%
  pivot_wider(names_from = correct, names_prefix = "correct", values_from = n) %>%
  mutate(across(starts_with('correct'), ~ if_else(is.na(.), 0L, .))) %>%
  mutate(accuracy = correctTRUE / (correctTRUE + correctFALSE)) %>%
  arrange(accuracy)

# worst-classified participant's videos
frame_average %>% 
  filter(!correct, str_starts(video, '0011'))

```

Prediction with frames combined via votes.

```{r}

frame_average_votes <- results %>% 
  group_by(video, actual_class, face_count) %>%
  summarise(
    prob_right = mean(predicted_class == 'right'), 
    frame_count = n(),
    .groups = "drop"
  )

ggplot(frame_average_votes, aes(x = prob_right, fill = actual_class)) +
  geom_histogram(alpha = 1/3, position = position_identity()) +
  ggtitle(glue("Predictive accuracy of classification (frames averaged)")) +
  theme(legend.position = "top")

ggplot(frame_average_votes, aes(x = prob_right, y = frame_count, colour = actual_class)) +
  geom_point(alpha = 0.2) +
  ggtitle("Accuracy by direction and frame count") +
  theme(legend.position = "top")

combined_accuracy_votes <- frame_average_votes %>% 
  mutate(correct = (prob_right > .5) == (actual_class == "right"))

combined_accuracy_votes %>%
  summarise(accuracy = mean(correct))

combined_accuracy_votes %>% 
  group_by(actual_class, face_count) %>%
  summarise(mean(correct))

accuracy_by_frame_count_votes <- combined_accuracy_votes %>%
  mutate(frames = cut(frame_count, 10)) %>%
  group_by(frames) %>%
  summarise(accuracy = mean(correct), n = n())
accuracy_by_frame_count_votes

ggplot(accuracy_by_frame_count_votes, aes(x = frames, y = accuracy)) +
  geom_point()


combined_accuracy_votes %>% 
  filter(!correct) %>%
  select(video, face_count, frame_count, correct) %>%
  arrange(-face_count, -frame_count)

# disagreements between votes-based and averaging pitch combination techniques
combined_accuracy_votes %>% 
  left_join(
    frame_average %>% select(video, correct, mean_pitch),
    by = "video",
    suffix = c("", "_using_mean_pitch")
  ) %>%
  filter(correct != correct_using_mean_pitch) %>%
  select(video, frame_count, prob_right, mean_pitch, actual_class) %>%
  arrange(prob_right, -mean_pitch)

```
